---
apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  labels:
    k8s-app: elk
  name: elk

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elk
  template:
    metadata:
      labels:
        k8s-app: elk
      name: elk
    spec:
      containers:
      - image: elk:local
        imagePullPolicy: IfNotPresent
        name: elk
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
---
apiVersion: v1

kind: Service

metadata:
  labels:
    k8s-app: elk-kibana
  name: elk-kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    nodePort: 30001
  selector:
    k8s-app: elk
---
apiVersion: v1

kind: Service

metadata:
  labels:
    k8s-app: elk-elasticsearch
  name: elk-elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    nodePort: 30002
  selector:
    k8s-app: elk
---
apiVersion: v1

kind: Service

metadata:
  labels:
    k8s-app: elk-logstash
  name: elk-logstash
spec:
  type: NodePort
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
    nodePort: 30003
  selector:
    k8s-app: elk
